services:
  - type: web
    name: yt-stream
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://melamrahul.github.io,https://ruvs.in,https://rahul.serv00.net
      - key: MAX_DURATION
        value: "1800"
    healthCheckPath: /healthz
    autoDeploy: true
